import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useConfig, useProject, getStageOverride, type VoiceoverResult } from "@/lib/store";
import { generateVoiceover, enhanceVoiceoverScript } from "@/lib/voiceover.functions";
import { resolvePromptTextById } from "@/lib/prompt-registry";
import { extractVoiceoverText } from "@/lib/voiceover-text";
import { DEFAULT_VOICEOVER_CONFIG } from "@/lib/types";
import { toast } from "sonner";
import { Download, RefreshCw, Sparkles } from "lucide-react";
import { StageHeader } from "@/components/stage/StageHeader";
import { ActivityPanel } from "@/components/stage/ActivityPanel";
import { useActivityLog } from "@/hooks/useActivityLog";
import { StageFooter } from "@/components/stage/StageFooter";
import { useHydrated } from "@/lib/use-hydrated";

export const Route = createFileRoute("/voiceover")({
  component: VoiceoverPage,
});

// OpenAI TTS was removed — Gemini + Murf are the supported providers.

// Google Gemini TTS prebuilt voices (30 voices)
const GEMINI_VOICES = [
  { id: "Kore", label: "Kore — firm, professional" },
  { id: "Puck", label: "Puck — upbeat, playful (recommended)" },
  { id: "Charon", label: "Charon — informative, deep" },
  { id: "Fenrir", label: "Fenrir — excitable, energetic" },
  { id: "Leda", label: "Leda — youthful, bright" },
  { id: "Aoede", label: "Aoede — breezy, warm" },
  { id: "Zephyr", label: "Zephyr — bright, expressive" },
  { id: "Orus", label: "Orus — firm, mature" },
  { id: "Callirrhoe", label: "Callirrhoe — easy-going" },
  { id: "Autonoe", label: "Autonoe — bright" },
  { id: "Enceladus", label: "Enceladus — breathy" },
  { id: "Iapetus", label: "Iapetus — clear" },
  { id: "Umbriel", label: "Umbriel — easy-going" },
  { id: "Algieba", label: "Algieba — smooth" },
  { id: "Despina", label: "Despina — smooth" },
  { id: "Erinome", label: "Erinome — clear" },
  { id: "Algenib", label: "Algenib — gravelly" },
  { id: "Rasalgethi", label: "Rasalgethi — informative" },
  { id: "Laomedeia", label: "Laomedeia — upbeat" },
  { id: "Achernar", label: "Achernar — soft" },
  { id: "Alnilam", label: "Alnilam — firm" },
  { id: "Schedar", label: "Schedar — even" },
  { id: "Gacrux", label: "Gacrux — mature" },
  { id: "Pulcherrima", label: "Pulcherrima — forward" },
  { id: "Achird", label: "Achird — friendly" },
  { id: "Zubenelgenubi", label: "Zubenelgenubi — casual" },
  { id: "Vindemiatrix", label: "Vindemiatrix — gentle" },
  { id: "Sadachbia", label: "Sadachbia — lively" },
  { id: "Sadaltager", label: "Sadaltager — knowledgeable" },
  { id: "Sulafat", label: "Sulafat — warm" },
];

const GEMINI_MODELS = [
  { id: "gemini-2.5-flash-preview-tts", label: "Flash TTS — free tier, fast" },
  { id: "gemini-2.5-pro-preview-tts", label: "Pro TTS — higher quality" },
];

// Voice direction is auto-generated by "Enhance with emotion" (script-specific).
// Hardcoded presets were removed — a universal preset never fits every script.

// cleanSpokenText + extractVoiceoverText moved to @/lib/voiceover-text
// so the live-prompt preview can call the exact same extractor the runtime uses.

function hashText(text?: string): string {
  let hash = 2166136261;
  for (const char of text ?? "") {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(36);
}

function formatSeconds(value?: number): string | null {
  if (!value || !Number.isFinite(value)) return null;
  return `${value.toFixed(1)}s`;
}

function VoiceoverPage() {
  const [project, setProject] = useProject();
  const [cfg, setCfg] = useConfig();
  const navigate = useNavigate();
  const vcfg = cfg.voiceover;

  const autoText = useMemo(() => extractVoiceoverText(project.script), [project.script]);
  const scriptHash = useMemo(() => hashText(project.script), [project.script]);
  const hasScript = Boolean(project.script?.trim());
  const hasStoredHash = Boolean(project.voiceoverScriptHash);
  const savedTextMatchesScript = hasStoredHash
    ? project.voiceoverScriptHash === scriptHash
    : !hasScript || !project.voiceoverText || project.voiceoverText === autoText;
  const currentVoiceover = savedTextMatchesScript ? project.voiceover : undefined;
  const takes = (savedTextMatchesScript ? project.voiceoverTakes : undefined) ?? [];
  const [text, setText] = useState(savedTextMatchesScript ? project.voiceoverText || autoText : autoText);
  const [dirty, setDirty] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [enhancing, setEnhancing] = useState(false);
  const activity = useActivityLog();
  

  useEffect(() => {
    if (!savedTextMatchesScript) {
      setText(autoText);
      setDirty(false);
      setProject({
        voiceoverText: undefined,
        voiceover: undefined,
        voiceoverTakes: undefined,
        voiceoverScriptHash: hasScript ? scriptHash : undefined,
      });
      return;
    }
    if (!dirty) setText(project.voiceoverText || autoText);
  }, [autoText, dirty, hasScript, project.voiceoverText, savedTextMatchesScript, scriptHash, setProject]);

  const setV = (patch: Partial<typeof vcfg>) =>
    setCfg({ voiceover: { ...vcfg, ...patch } });

  // Migrate legacy preset label "Natalie (default)" → "Dirk (default)"
  useEffect(() => {
    const presets = vcfg.murfVoicePresets ?? [];
    if (presets.some((p) => p.name === "Natalie (default)")) {
      setV({
        murfVoicePresets: presets.map((p) =>
          p.name === "Natalie (default)" ? { ...p, name: "Dirk (default)" } : p,
        ),
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);



  async function enhance() {
    if (!text.trim()) return toast.error("Nothing to enhance — add script text first.");
    setEnhancing(true);
    activity.start("enhancing script with emotion cues…");
    try {
      const isCommentary = project.mode === "analysis";
      const a = project.analysis;
      const src = project.analysisSource;
      const context = isCommentary
        ? {
            title: src?.title ?? project.meta?.title,
            tone: a?.tone,
            pacing: a?.pacing,
            topics: a?.topics,
            entities: a?.entities,
            targetAudience: a?.targetAudience,
            angle: (() => {
              const raw = (project as any).selectedAngle ?? a?.commentaryAngles?.[0];
              if (raw == null) return undefined;
              if (typeof raw === "string") return raw;
              if (typeof raw === "object") return (raw as any).angle ?? (raw as any).text ?? (raw as any).label;
              return String(raw);
            })(),

            summary: a?.summary,
          }
        : undefined;
      const res = await enhanceVoiceoverScript({
        data: {
          text: text.trim(),
          provider: vcfg.provider,
          vibe: vcfg.instructions,
          mode: isCommentary ? "commentary" : "product",
          context,
          promptTemplateCommentary: resolvePromptTextById(cfg, "voiceover.enhanceCommentary"),
          promptTemplateProduct: resolvePromptTextById(cfg, "voiceover.enhanceProduct"),
          override: getStageOverride(cfg, "voiceover"),
        },
      });
      setText(res.text);
      setDirty(true);
      setProject({ voiceoverText: res.text, voiceover: undefined, voiceoverTakes: undefined, voiceoverScriptHash: scriptHash });
      const patch: Partial<typeof vcfg> = { instructions: res.instructions };
      if (vcfg.provider === "gemini") {
        if (res.scene) patch.geminiScene = res.scene;
        if (res.sampleContext) patch.geminiSampleContext = res.sampleContext;
      }
      setV(patch);
      const successMsg =
        (isCommentary ? "Commentary humour direction · " : "Emotion cues added · ") +
        (vcfg.provider === "gemini" ? "scene + tags generated" : "bespoke direction generated");
      activity.stop(successMsg, "ok");
      toast.success(successMsg);
    } catch (e) {
      const msg = (e as Error).message;
      activity.stop(msg, "error");
      toast.error(msg);
    } finally {
      setEnhancing(false);
    }
  }


  async function generate() {
    if (!text.trim()) return toast.error("No voiceover text.");
    const validKeys = vcfg.geminiApiKeys.map((k) => k.trim()).filter(Boolean);
    if (vcfg.provider === "gemini" && validKeys.length === 0) {
      return toast.error("Add at least one Gemini API key in Settings → Voiceover.");
    }
    if (vcfg.provider === "murf") {
      const missing: string[] = [];
      if (!vcfg.murfVoiceId.trim()) missing.push("voice id");
      if (missing.length) {
        return toast.error(`Murf.ai is missing: ${missing.join(", ")}. Fill them in Voice config → Murf.`);
      }
    }
    setGenerating(true);
    activity.start(`synthesising voiceover · ${vcfg.provider}…`);
    activity.log(`${text.trim().length} chars · voice ${vcfg.provider === "gemini" ? vcfg.geminiVoice : vcfg.provider === "murf" ? vcfg.murfVoiceId : vcfg.voice}`);
    try {
      const res = await generateVoiceover({
        data: {
          text: text.trim(),
          provider: vcfg.provider,
          instructions: vcfg.instructions,
          speed: vcfg.speed,
          voice: vcfg.voice,
          format: vcfg.format,
          model: vcfg.model,
          geminiVoice: vcfg.geminiVoice,
          geminiModel: vcfg.geminiModel,
          geminiApiKeys: validKeys,
          geminiSpeed: vcfg.geminiSpeed,
          geminiScene: vcfg.geminiScene,
          geminiSampleContext: vcfg.geminiSampleContext,
          chunkMode: vcfg.chunkMode,
          murfIdToken: vcfg.murfIdToken,
          murfProjectId: vcfg.murfProjectId || DEFAULT_VOICEOVER_CONFIG.murfProjectId,
          murfWorkspaceId: vcfg.murfWorkspaceId,
          murfDuid: vcfg.murfDuid,
          murfVoiceId: vcfg.murfVoiceId,
          murfLanguageCode: vcfg.murfLanguageCode,
          murfStyle: vcfg.murfStyle,
          murfSpeed: vcfg.murfSpeed,
          murfRefreshToken: vcfg.murfRefreshToken,
          murfFirebaseApiKey: vcfg.murfFirebaseApiKey,
        },
      });
      const prevTakes = (savedTextMatchesScript ? project.voiceoverTakes : undefined) ?? [];
      const nextTakes = [...prevTakes, res].slice(-6);
      setProject({ voiceover: res, voiceoverTakes: nextTakes, voiceoverText: text, voiceoverScriptHash: scriptHash });
      const speedNote = (res.provider === "gemini" || res.provider === "murf") && res.sourceDurationSec && res.durationSec
        ? ` · ${res.sourceDurationSec.toFixed(1)}s → ${res.durationSec.toFixed(1)}s at ${res.speed.toFixed(2)}×`
        : "";
      const providerLabel = res.provider === "gemini" ? "Gemini" : res.provider === "murf" ? "Murf.ai" : "OpenAI";
      const successMsg = `Voiceover ready · ${res.sentenceCount ?? 1} sentence${(res.sentenceCount ?? 1) === 1 ? "" : "s"} merged · ${res.chars} chars · ${providerLabel}${speedNote}`;
      activity.stop(successMsg, "ok");
      toast.success(successMsg);
    } catch (e) {
      const msg = (e as Error).message;
      activity.stop(msg, "error");
      toast.error(msg);
    } finally {
      setGenerating(false);
    }
  }

  function srcFor(vo: VoiceoverResult): string {
    return vo.audioUrl
      || (vo.audioBase64 ? `data:${vo.mimeType};base64,${vo.audioBase64}` : "");
  }

  function downloadTake(vo: VoiceoverResult, idx?: number) {
    const src = srcFor(vo);
    if (!src) return;
    const a = document.createElement("a");
    a.href = src;
    const safe = (project.meta?.title ?? "voiceover").replace(/[^a-z0-9-_]+/gi, "_").slice(0, 60);
    const suffix = typeof idx === "number" ? `_take${idx + 1}` : "";
    a.download = `${safe}_${vo.provider}_${vo.voice}${suffix}.${vo.format}`;
    a.click();
  }

  function deleteTake(genAt: number) {
    const next = takes.filter((t) => t.generatedAt !== genAt);
    const isCurrent = currentVoiceover?.generatedAt === genAt;
    setProject({
      voiceoverTakes: next.length ? next : undefined,
      voiceover: isCurrent ? next[next.length - 1] : currentVoiceover,
    });
  }

  function clearTakes() {
    setProject({ voiceoverTakes: undefined, voiceover: undefined });
  }




  const wordCount = text.trim().split(/\s+/).filter(Boolean).length;
  const chars = text.trim().length;
  const hydrated = useHydrated();
  const isGemini = hydrated && vcfg.provider === "gemini";
  const isMurf = hydrated && vcfg.provider === "murf";

  return (
    <AppShell>
      <StageHeader
        current="voiceover"
        title="Voiceover generator"
        purpose="Turn the script into narrated audio — configure the voice on the right, then generate."
      />
      <div className="mb-4"><ActivityPanel activity={activity} /></div>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
        <div className="space-y-6">
          {/* Text */}
          <section className="rounded-lg border border-border bg-card p-5">
            <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
              <h3 className="font-mono text-sm font-semibold">
                Voiceover text{" "}
                <span className="text-muted-foreground">
                  · {hydrated ? wordCount : 0} words · {hydrated ? chars : 0} chars
                </span>
              </h3>
              <div className="flex items-center gap-3">
                <Button
                  size="sm"
                  onClick={enhance}
                  disabled={enhancing || !text.trim()}
                  className="h-8 gap-1.5 font-mono text-[11px]"
                >
                  <Sparkles className="h-3 w-3" />
                  {enhancing ? "adding emotion…" : "✨ enhance with emotion"}
                </Button>
                <button
                  onClick={() => {
                    setText(autoText);
                    setDirty(false);
                    toast.success("Restored from script");
                  }}
                  className="font-mono text-[10px] text-muted-foreground hover:text-primary"
                >
                  [reload from script]
                </button>
              </div>
            </div>
            <p className="mb-3 text-xs text-muted-foreground">
              Click <span className="text-primary">enhance with emotion</span> to rewrite this text with strategic pacing (…, —), emphasis, and a bespoke voice-direction block tailored to <em>this</em> script. Then generate.
            </p>
            <Textarea
              value={text}
              onChange={(e) => {
                setText(e.target.value);
                setDirty(true);
              }}
              rows={14}
              className="font-mono text-sm leading-relaxed"
              placeholder="Paste or edit the voiceover script here…"
            />
          </section>

          {/* Player · one entry per take (newest first) */}
          <section className="rounded-lg border border-border bg-card p-5">
            <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
              <h3 className="font-mono text-sm font-semibold">
                Generated audio
                {takes.length > 0 && (
                  <span className="ml-2 font-mono text-[10px] text-muted-foreground">
                    · {takes.length} take{takes.length === 1 ? "" : "s"} this session
                  </span>
                )}
              </h3>
              {takes.length > 0 && (
                <button
                  onClick={clearTakes}
                  className="font-mono text-[10px] text-muted-foreground hover:text-destructive"
                >
                  [clear all]
                </button>
              )}
            </div>
            {takes.length > 0 ? (
              <ul className="space-y-3">
                {[...takes].reverse().map((vo, i) => {
                  const idx = takes.length - 1 - i;
                  const isLatest = i === 0;
                  const providerLabel = vo.provider === "gemini" ? "Gemini" : vo.provider === "murf" ? "Murf.ai" : "OpenAI";
                  return (
                    <li
                      key={vo.generatedAt}
                      className={`rounded-md border p-3 ${isLatest ? "border-primary/40 bg-primary/5" : "border-border bg-background/40"}`}
                    >
                      <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
                        <div className="font-mono text-[11px] text-muted-foreground">
                          <span className="mr-1 font-semibold text-foreground">Take {idx + 1}</span>
                          · {providerLabel} · {vo.voice} · {vo.speed}× · {vo.format}
                          {formatSeconds(vo.durationSec) ? ` · ${formatSeconds(vo.durationSec)}` : ""}
                          {isLatest && <span className="ml-2 rounded bg-primary/15 px-1.5 py-0.5 text-[9px] uppercase text-primary">latest</span>}
                        </div>
                        <div className="flex items-center gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => downloadTake(vo, idx)}
                            className="h-7 gap-1.5 font-mono text-[10px]"
                          >
                            <Download className="h-3 w-3" /> download
                          </Button>
                          <button
                            onClick={() => deleteTake(vo.generatedAt)}
                            className="font-mono text-[10px] text-muted-foreground hover:text-destructive"
                            title="Remove this take"
                          >
                            [remove]
                          </button>
                        </div>
                      </div>
                      <audio controls className="w-full" src={srcFor(vo)} />
                      {(vo.provider === "gemini" || vo.provider === "murf") && vo.sourceDurationSec && vo.durationSec && (
                        <p className="mt-2 font-mono text-[10px] text-muted-foreground">
                          Speed applied after generation: {vo.sourceDurationSec.toFixed(1)}s native → {vo.durationSec.toFixed(1)}s output, pitch preserved.
                        </p>
                      )}
                    </li>
                  );
                })}
              </ul>
            ) : (
              <div className="rounded-md border border-dashed border-border py-10 text-center font-mono text-xs text-muted-foreground">
                No audio yet · configure voice on the right, then hit generate. Every generation is kept so you can compare providers side-by-side.
              </div>
            )}
          </section>




        </div>

        {/* Sidebar */}
        <aside className="space-y-5 rounded-lg border border-border bg-card p-5 h-fit lg:sticky lg:top-4">
          <div>
            <h3 className="mb-3 font-mono text-sm font-semibold">Voice config</h3>
            {!hydrated ? (
              <div className="rounded-md border border-dashed border-border p-6 text-center font-mono text-[11px] text-muted-foreground">loading config…</div>
            ) : (
            <div className="space-y-4">
              <div>
                <Label className="font-mono text-[11px] uppercase text-muted-foreground">Provider</Label>
                <Select
                  value={vcfg.provider}
                  onValueChange={(v) => setV({ provider: v as typeof vcfg.provider })}
                >
                  <SelectTrigger className="mt-1"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="gemini">Google Gemini TTS (BYO key)</SelectItem>
                    <SelectItem value="murf">Murf.ai (BYO session)</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              {isGemini ? (
                <>
                  <div>
                    <Label className="font-mono text-[11px] uppercase text-muted-foreground">Gemini voice</Label>
                    <Select value={vcfg.geminiVoice} onValueChange={(v) => setV({ geminiVoice: v })}>
                      <SelectTrigger className="mt-1"><SelectValue /></SelectTrigger>
                      <SelectContent className="max-h-72">
                        {GEMINI_VOICES.map((v) => (
                          <SelectItem key={v.id} value={v.id}>{v.label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label className="font-mono text-[11px] uppercase text-muted-foreground">Gemini model</Label>
                    <Select value={vcfg.geminiModel} onValueChange={(v) => setV({ geminiModel: v })}>
                      <SelectTrigger className="mt-1"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {GEMINI_MODELS.map((m) => (
                          <SelectItem key={m.id} value={m.id}>{m.label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <div className="flex items-center justify-between">
                      <Label className="font-mono text-[11px] uppercase text-muted-foreground">Speed</Label>
                      <span className="font-mono text-[11px] text-primary">{vcfg.geminiSpeed.toFixed(2)}×</span>
                    </div>
                    <Slider
                      min={0.5}
                      max={2}
                      step={0.05}
                      value={[vcfg.geminiSpeed]}
                      onValueChange={([v]) => setV({ geminiSpeed: v })}
                      className="mt-2"
                    />
                    <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                      Applied after generation with pitch-preserving time-stretch. Regenerate to hear speed changes.
                    </p>
                  </div>
                  <div>
                    <Label className="font-mono text-[11px] uppercase text-muted-foreground">
                      Scene
                    </Label>
                    <Input
                      value={vcfg.geminiScene}
                      onChange={(e) => setV({ geminiScene: e.target.value })}
                      placeholder="e.g. The Sound Stage Booth."
                      className="mt-1 font-mono text-xs"
                    />
                    <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                      Physical setting / mic environment. Auto-filled by ✨ enhance.
                    </p>
                  </div>
                  <div>
                    <Label className="font-mono text-[11px] uppercase text-muted-foreground">
                      Sample context
                    </Label>
                    <Textarea
                      value={vcfg.geminiSampleContext}
                      onChange={(e) => setV({ geminiSampleContext: e.target.value })}
                      rows={3}
                      placeholder="e.g. Premium commercial. Dynamic pacing—starts intrigued, ends punchy."
                      className="mt-1 font-mono text-xs"
                    />
                    <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                      Tone + pacing arc for THIS script. Auto-filled by ✨ enhance.
                    </p>
                  </div>
                  <div className="rounded-md border border-dashed border-border p-3">
                    <div className="font-mono text-[10px] uppercase text-muted-foreground">API keys</div>
                    <div className="mt-1 font-mono text-[11px]">
                      {vcfg.geminiApiKeys.filter((k) => k.trim()).length > 0 ? (
                        <span className="text-primary">
                          {vcfg.geminiApiKeys.filter((k) => k.trim()).length} key
                          {vcfg.geminiApiKeys.filter((k) => k.trim()).length === 1 ? "" : "s"} configured
                        </span>
                      ) : (
                        <span className="text-destructive">No keys — add in Settings</span>
                      )}
                    </div>
                    <a
                      href="/settings"
                      className="mt-1 inline-block font-mono text-[10px] text-primary hover:underline"
                    >
                      → manage in Settings
                    </a>
                  </div>
                </>
              ) : isMurf ? (
                <>
                  <div>
                    <Label className="font-mono text-[11px] uppercase text-muted-foreground">Voice</Label>
                    <div className="mt-1 flex gap-2">
                      <select
                        value={(vcfg.murfVoicePresets ?? []).some((p) => p.id === vcfg.murfVoiceId) ? vcfg.murfVoiceId : "__custom__"}
                        onChange={(e) => {
                          const val = e.target.value;
                          if (val !== "__custom__") setV({ murfVoiceId: val });
                        }}
                        className="flex-1 rounded-md border border-input bg-background px-2 py-1 font-mono text-xs"
                      >
                        {(vcfg.murfVoicePresets ?? []).map((p) => {
                          const displayName = p.id === "VM01721940536261616" ? "Dirk (default)" : p.name;
                          return (
                            <option key={p.id} value={p.id}>{displayName} — {p.id}</option>
                          );
                        })}
                        <option value="__custom__">Custom (edit ID below)</option>
                      </select>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        className="font-mono text-[11px]"
                        onClick={() => {
                          const name = window.prompt("Voice name (e.g. Dirk)")?.trim();
                          if (!name) return;
                          const id = window.prompt(`Voice ID for "${name}" (e.g. VM01721940536261616)`)?.trim();
                          if (!id) return;
                          const presets = [...(vcfg.murfVoicePresets ?? [])];
                          const idx = presets.findIndex((p) => p.id === id);
                          if (idx >= 0) presets[idx] = { name, id };
                          else presets.push({ name, id });
                          setV({ murfVoicePresets: presets, murfVoiceId: id });
                        }}
                      >
                        + Add
                      </Button>
                      {(vcfg.murfVoicePresets ?? []).some((p) => p.id === vcfg.murfVoiceId) && (vcfg.murfVoicePresets ?? []).length > 1 && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="font-mono text-[11px] text-destructive"
                          onClick={() => {
                            const presets = (vcfg.murfVoicePresets ?? []).filter((p) => p.id !== vcfg.murfVoiceId);
                            setV({ murfVoicePresets: presets, murfVoiceId: presets[0]?.id ?? "" });
                          }}
                        >
                          Remove
                        </Button>
                      )}
                    </div>
                    <Input
                      value={vcfg.murfVoiceId}
                      onChange={(e) => setV({ murfVoiceId: e.target.value })}
                      placeholder="VM01721940536261616"
                      className="mt-2 font-mono text-xs"
                    />
                    <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                      Pick a saved voice or click <span className="text-primary">+ Add</span> to save a new one with a friendly name. Voice ID comes from Murf Studio URL / devtools.
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <Label className="font-mono text-[11px] uppercase text-muted-foreground">Language</Label>
                      <Input value={vcfg.murfLanguageCode} onChange={(e) => setV({ murfLanguageCode: e.target.value })} placeholder="en_US" className="mt-1 font-mono text-xs" />
                    </div>
                    <div>
                      <Label className="font-mono text-[11px] uppercase text-muted-foreground">Style</Label>
                      <Input value={vcfg.murfStyle} onChange={(e) => setV({ murfStyle: e.target.value })} placeholder="Narration" className="mt-1 font-mono text-xs" />
                    </div>
                  </div>
                  <div>
                    <div className="flex items-center justify-between">
                      <Label className="font-mono text-[11px] uppercase text-muted-foreground">Speed</Label>
                      <span className="font-mono text-[11px] text-primary">{vcfg.murfSpeed.toFixed(2)}×</span>
                    </div>
                    <Slider
                      min={0.5}
                      max={2}
                      step={0.05}
                      value={[vcfg.murfSpeed]}
                      onValueChange={([v]) => setV({ murfSpeed: v })}
                      className="mt-2"
                    />
                    <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                      Applied after generation with pitch-preserving time-stretch — voice sounding stays identical.
                    </p>
                  </div>
                  <div className="rounded-md border border-dashed border-border p-3 space-y-2">
                    <div className="font-mono text-[10px] uppercase text-muted-foreground">Murf session</div>
                    <div>
                      <Label className="font-mono text-[10px] text-muted-foreground">refresh_token (recommended — auto-mints idtoken each run)</Label>
                      <Textarea
                        value={vcfg.murfRefreshToken}
                        onChange={(e) => setV({ murfRefreshToken: e.target.value })}
                        rows={2}
                        placeholder="AMf-vB…"
                        className="mt-1 font-mono text-[10px] leading-tight"
                      />
                      <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                        Grab from Murf devtools once (Application → IndexedDB → firebaseLocalStorage) — long-lived, no more hourly refresh.
                      </p>
                    </div>
                    <div>
                      <Label className="font-mono text-[10px] text-muted-foreground">Firebase Web API key</Label>
                      <Input value={vcfg.murfFirebaseApiKey} onChange={(e) => setV({ murfFirebaseApiKey: e.target.value })} placeholder="AIzaSy…" className="mt-1 font-mono text-[10px]" />
                    </div>
                    <div>
                      <Label className="font-mono text-[10px] text-muted-foreground">Project ID</Label>
                      <Input value={vcfg.murfProjectId} onChange={(e) => setV({ murfProjectId: e.target.value })} placeholder="P017843231938171NQ" className="mt-1 font-mono text-[10px]" />
                    </div>
                    <p className="font-mono text-[10px] text-muted-foreground">
                      The refresh_token auto-mints a fresh idtoken on every run — no need for workspace id / duid.
                    </p>
                  </div>

                </>
              ) : null}

              <div>
                <div className="flex items-center justify-between">
                  <Label className="font-mono text-[11px] uppercase text-muted-foreground">
                    Voice direction (instructions)
                  </Label>
                  <button
                    type="button"
                    onClick={() => setV({ instructions: DEFAULT_VOICEOVER_CONFIG.instructions })}
                    title="Reset only this field to the product-review default"
                    className="font-mono text-[10px] text-muted-foreground hover:text-primary"
                  >
                    <RefreshCw className="mr-1 inline h-3 w-3" /> reset to default
                  </button>
                </div>
                <Textarea
                  value={vcfg.instructions}
                  onChange={(e) => setV({ instructions: e.target.value })}
                  rows={8}
                  placeholder="Auto-filled by Enhance with emotion — or write your own script-specific direction here."
                  className="mt-1 font-mono text-xs"
                />
                <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                  Baseline is tuned for product-review explainers (energetic, fast, no breaths). <em>Enhance</em> rewrites it per script; reset restores the baseline.
                </p>
              </div>
            </div>
            )}
          </div>

          {!isMurf && (
            <div>
              <Label className="font-mono text-[11px] uppercase text-muted-foreground">
                Generation mode
              </Label>
              <Select
                value={vcfg.chunkMode}
                onValueChange={(v) => setV({ chunkMode: v as typeof vcfg.chunkMode })}
              >
                <SelectTrigger className="mt-1"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="full">Full script in one go (1 request · coherent delivery, matches AI Studio)</SelectItem>
                  <SelectItem value="sentence">Per-sentence (many requests · tone/prosody drifts between sentences)</SelectItem>
                </SelectContent>
              </Select>
              <p className="mt-1 font-mono text-[10px] text-muted-foreground">
                {vcfg.chunkMode === "full"
                  ? isGemini
                    ? "1 request — same behaviour as Google AI Studio. Prosody, pacing, and emotional arc stay consistent across the whole script. Fits the free-tier 3 RPM cap."
                    : "1 request — fastest. Quality may drift on very long scripts."
                  : isGemini
                    ? `⚠ ~${Math.max(1, text.trim().split(/[.!?…]+/).filter((s) => s.trim()).length)} requests — Gemini re-rolls prosody per request, so each sentence sounds slightly different. Will also hit the free-tier 3 RPM cap. Prefer "full" mode.`
                    : `~${Math.max(1, text.trim().split(/[.!?…]+/).filter((s) => s.trim()).length)} requests — every sentence rendered fresh for consistent quality.`}
              </p>
            </div>
          )}


          <Button
            onClick={generate}
            disabled={generating || !text.trim() || (isGemini && vcfg.geminiApiKeys.filter((k) => k.trim()).length === 0)}
            className="w-full font-mono"
          >
            {generating
              ? "generating audio…"
              : currentVoiceover
                ? "↻ regenerate voiceover"
                : "🎙 generate voiceover"}
          </Button>

          <div className="border-t border-border pt-4 font-mono text-[10px] leading-relaxed text-muted-foreground">
            <div>engine: <span className="text-foreground">{isGemini ? `Gemini · ${vcfg.geminiModel}` : isMurf ? "Murf.ai · quick-audition-preview" : `OpenAI · ${vcfg.model}`}</span></div>
            <div>chars: <span className={chars ? "text-primary" : ""}>{chars}</span></div>
            {!isGemini && (
              <div>chunks: <span className="text-foreground">{Math.max(1, Math.ceil(chars / 1800))}</span></div>
            )}
            <div className="mt-2 text-muted-foreground/70">
              Tip: run <span className="text-primary">✨ enhance</span> once per script, then generate. It writes emotion cues INTO the text and a bespoke direction block.
            </div>
          </div>
        </aside>
      </div>

      <StageFooter
        current="voiceover"
        nextLabel={project.seo ? "→ regenerate SEO pack" : "→ continue to SEO pack"}
        primary={
          project.seo ? (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => navigate({ to: "/seo" })}
              className="font-mono text-xs text-muted-foreground"
            >
              view existing SEO pack
            </Button>
          ) : null
        }
      />
    </AppShell>
  );
}
