/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CommentaryRouteImport } from './routes/commentary'
import { Route as FairUseRouteImport } from './routes/fair-use'
import { Route as FramesRouteImport } from './routes/frames'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ScriptRouteImport } from './routes/script'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TranscriptRouteImport } from './routes/transcript'
import { Route as VoiceoverRouteImport } from './routes/voiceover'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiExtractFramesRouteImport } from './routes/api/extract-frames'
import { Route as ApiHealthzRouteImport } from './routes/api/healthz'
import { Route as ApiMediaProxyRouteImport } from './routes/api/media-proxy'
import { Route as ApiSessionsRouteImport } from './routes/api/sessions'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiYoutubeCookiesRouteImport } from './routes/api/youtube-cookies'
import { Route as ApiYoutubeDebugRouteImport } from './routes/api/youtube-debug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentaryRoute = CommentaryRouteImport.update({
  id: '/commentary',
  path: '/commentary',
  getParentRoute: () => rootRouteImport,
} as any)
const FairUseRoute = FairUseRouteImport.update({
  id: '/fair-use',
  path: '/fair-use',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesRoute = FramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptRoute = ScriptRouteImport.update({
  id: '/script',
  path: '/script',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptRoute = TranscriptRouteImport.update({
  id: '/transcript',
  path: '/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceoverRoute = VoiceoverRouteImport.update({
  id: '/voiceover',
  path: '/voiceover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractFramesRoute = ApiExtractFramesRouteImport.update({
  id: '/api/extract-frames',
  path: '/api/extract-frames',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthzRoute = ApiHealthzRouteImport.update({
  id: '/api/healthz',
  path: '/api/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaProxyRoute = ApiMediaProxyRouteImport.update({
  id: '/api/media-proxy',
  path: '/api/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsRoute = ApiSessionsRouteImport.update({
  id: '/api/sessions',
  path: '/api/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeCookiesRoute = ApiYoutubeCookiesRouteImport.update({
  id: '/api/youtube-cookies',
  path: '/api/youtube-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeDebugRoute = ApiYoutubeDebugRouteImport.update({
  id: '/api/youtube-debug',
  path: '/api/youtube-debug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/commentary': typeof CommentaryRoute
  '/fair-use': typeof FairUseRoute
  '/frames': typeof FramesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/transcript': typeof TranscriptRoute
  '/voiceover': typeof VoiceoverRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/extract-frames': typeof ApiExtractFramesRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube-cookies': typeof ApiYoutubeCookiesRoute
  '/api/youtube-debug': typeof ApiYoutubeDebugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/commentary': typeof CommentaryRoute
  '/fair-use': typeof FairUseRoute
  '/frames': typeof FramesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/transcript': typeof TranscriptRoute
  '/voiceover': typeof VoiceoverRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/extract-frames': typeof ApiExtractFramesRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube-cookies': typeof ApiYoutubeCookiesRoute
  '/api/youtube-debug': typeof ApiYoutubeDebugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/commentary': typeof CommentaryRoute
  '/fair-use': typeof FairUseRoute
  '/frames': typeof FramesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/script': typeof ScriptRoute
  '/seo': typeof SeoRoute
  '/settings': typeof SettingsRoute
  '/transcript': typeof TranscriptRoute
  '/voiceover': typeof VoiceoverRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/extract-frames': typeof ApiExtractFramesRoute
  '/api/healthz': typeof ApiHealthzRoute
  '/api/media-proxy': typeof ApiMediaProxyRoute
  '/api/sessions': typeof ApiSessionsRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube-cookies': typeof ApiYoutubeCookiesRoute
  '/api/youtube-debug': typeof ApiYoutubeDebugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/commentary'
    | '/fair-use'
    | '/frames'
    | '/login'
    | '/products'
    | '/script'
    | '/seo'
    | '/settings'
    | '/transcript'
    | '/voiceover'
    | '/api/auth'
    | '/api/extract-frames'
    | '/api/healthz'
    | '/api/media-proxy'
    | '/api/sessions'
    | '/api/transcribe'
    | '/api/youtube-cookies'
    | '/api/youtube-debug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/commentary'
    | '/fair-use'
    | '/frames'
    | '/login'
    | '/products'
    | '/script'
    | '/seo'
    | '/settings'
    | '/transcript'
    | '/voiceover'
    | '/api/auth'
    | '/api/extract-frames'
    | '/api/healthz'
    | '/api/media-proxy'
    | '/api/sessions'
    | '/api/transcribe'
    | '/api/youtube-cookies'
    | '/api/youtube-debug'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/commentary'
    | '/fair-use'
    | '/frames'
    | '/login'
    | '/products'
    | '/script'
    | '/seo'
    | '/settings'
    | '/transcript'
    | '/voiceover'
    | '/api/auth'
    | '/api/extract-frames'
    | '/api/healthz'
    | '/api/media-proxy'
    | '/api/sessions'
    | '/api/transcribe'
    | '/api/youtube-cookies'
    | '/api/youtube-debug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CommentaryRoute: typeof CommentaryRoute
  FairUseRoute: typeof FairUseRoute
  FramesRoute: typeof FramesRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  ScriptRoute: typeof ScriptRoute
  SeoRoute: typeof SeoRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptRoute: typeof TranscriptRoute
  VoiceoverRoute: typeof VoiceoverRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiExtractFramesRoute: typeof ApiExtractFramesRoute
  ApiHealthzRoute: typeof ApiHealthzRoute
  ApiMediaProxyRoute: typeof ApiMediaProxyRoute
  ApiSessionsRoute: typeof ApiSessionsRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiYoutubeCookiesRoute: typeof ApiYoutubeCookiesRoute
  ApiYoutubeDebugRoute: typeof ApiYoutubeDebugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commentary': {
      id: '/commentary'
      path: '/commentary'
      fullPath: '/commentary'
      preLoaderRoute: typeof CommentaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-use': {
      id: '/fair-use'
      path: '/fair-use'
      fullPath: '/fair-use'
      preLoaderRoute: typeof FairUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames': {
      id: '/frames'
      path: '/frames'
      fullPath: '/frames'
      preLoaderRoute: typeof FramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/script': {
      id: '/script'
      path: '/script'
      fullPath: '/script'
      preLoaderRoute: typeof ScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcript': {
      id: '/transcript'
      path: '/transcript'
      fullPath: '/transcript'
      preLoaderRoute: typeof TranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voiceover': {
      id: '/voiceover'
      path: '/voiceover'
      fullPath: '/voiceover'
      preLoaderRoute: typeof VoiceoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-frames': {
      id: '/api/extract-frames'
      path: '/api/extract-frames'
      fullPath: '/api/extract-frames'
      preLoaderRoute: typeof ApiExtractFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healthz': {
      id: '/api/healthz'
      path: '/api/healthz'
      fullPath: '/api/healthz'
      preLoaderRoute: typeof ApiHealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media-proxy': {
      id: '/api/media-proxy'
      path: '/api/media-proxy'
      fullPath: '/api/media-proxy'
      preLoaderRoute: typeof ApiMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions': {
      id: '/api/sessions'
      path: '/api/sessions'
      fullPath: '/api/sessions'
      preLoaderRoute: typeof ApiSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube-cookies': {
      id: '/api/youtube-cookies'
      path: '/api/youtube-cookies'
      fullPath: '/api/youtube-cookies'
      preLoaderRoute: typeof ApiYoutubeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube-debug': {
      id: '/api/youtube-debug'
      path: '/api/youtube-debug'
      fullPath: '/api/youtube-debug'
      preLoaderRoute: typeof ApiYoutubeDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CommentaryRoute: CommentaryRoute,
  FairUseRoute: FairUseRoute,
  FramesRoute: FramesRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  ScriptRoute: ScriptRoute,
  SeoRoute: SeoRoute,
  SettingsRoute: SettingsRoute,
  TranscriptRoute: TranscriptRoute,
  VoiceoverRoute: VoiceoverRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiExtractFramesRoute: ApiExtractFramesRoute,
  ApiHealthzRoute: ApiHealthzRoute,
  ApiMediaProxyRoute: ApiMediaProxyRoute,
  ApiSessionsRoute: ApiSessionsRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiYoutubeCookiesRoute: ApiYoutubeCookiesRoute,
  ApiYoutubeDebugRoute: ApiYoutubeDebugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
